name: Database Backup

on:
  push:
    branches:
      - master

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3.3.0

    - name: Get PostgreSQL Container ID
      id: get_container_id
      run: |
        CONTAINER_ID=$(docker ps -q --filter "ancestor=postgres:14")
        echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV

    - name: Print PostgreSQL Container ID
      run: echo ${{ env.CONTAINER_ID }}

    - name: Backup PostgreSQL database
      env:
        CONTAINER_ID: ${{ env.CONTAINER_ID }}
      run: |
        BACKUP_FILE_NAME=db_backup_$(date +%Y%m%d%H%M%S).sql
        docker exec -t $CONTAINER_ID pg_dump --no-owner -U quarkus quarkus -f /tmp/$BACKUP_FILE_NAME
        docker cp $CONTAINER_ID:/tmp/$BACKUP_FILE_NAME ./
        echo "Backup saved as $BACKUP_FILE_NAME"
      
    - name: Upload Backup to GitHub Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: db-backup
        path: db_backup_*.sql
