name: Backup PostgreSQL Database

on:
  schedule:
    - cron: '*/1 * * * *'  

jobs:
  backup:
    runs-on: [self-hosted, windows, x64]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4.1.5

    - name: Get PostgreSQL Container ID
      id: get_container_id
      run: |
        $CONTAINER_ID = & docker ps -q --filter "ancestor=postgres:14"
        Write-Host "CONTAINER_ID=$CONTAINER_ID"
        Set-Content -Path $env:GITHUB_ENV -Value "CONTAINER_ID=$CONTAINER_ID"

    - name: Run PostgreSQL Backup
      run: |
        docker exec -t $env:CONTAINER_ID pg_dump --no-owner -U quarkus quarkus > psql-backup.sql
